# Clear sky background

import turtle as t
t.speed(99999)

# Bee element
def bee(x, y, angle):
    t.pensize(1)
    t.pencolor('#753F0F')
    t.fillcolor('#F0C884')
    t.goto(x, y)
    t.down()
    t.begin_fill()
    t.right(angle)
    t.circle(20,110)
    t.left(75)
    t.circle(20,110)
    t.left(125)
    t.end_fill()
    t.penup()
    t.forward(20)
    t.pendown()
    t.pencolor('#559FFA')
    t.fillcolor('#DDEEEE')
    t.begin_fill()
    t.left(65)
    t.forward(20)
    t.left(55)
    t.circle(8,180)
    t.forward(10)
    t.right(45)
    t.forward(10)
    t.circle(8,166)
    t.left(62)
    t.forward(21)
    t.end_fill()
    t.up()
    t.forward(4)
    t.pencolor('#753F0F')
    t.pensize(3)
    t.left(60)
    t.forward(8)
    t.left(90)
    t.down()
    t.forward(11)
    t.right(113)
    t.up()
    t.forward(7)
    t.right(75)
    t.down()
    t.forward(6)
    t.up()
    t.right(70)
    t.forward(10)
    t.right(100)
    t.down()
    t.forward(13)
    t.up()
    t.left(130)
    t.forward(15)
    t.right(40)
    t.up()
    t.home()

# The main function
def sunshine():

    # Sky color
    t.pencolor('#CAF8FA')
    t.fillcolor('#CAF8FA')
    t.begin_fill()
    t.forward(300)
    t.left(90)
    t.forward(200)
    t.left(90)
    t.forward(600)
    t.left(90)
    t.forward(200)
    t.left(90)
    t.forward(300)
    t.end_fill()
    t.up()

    # Sun
    t.pencolor('Yellow')
    t.fillcolor('Yellow')
    t.pensize(5)
    t.goto(150, 150)
    t.down()
    t.begin_fill()
    t.circle(-30)
    t.end_fill()
    t.right(90)
    t.forward(30)
    for i in range(1,6):
        t.forward(100)
        t.back(100)
        t.right(36)
        t.forward(80)
        t.back(80)
        t.right(36)
    t.up()

    # Bees
    bee(-160, 60, -50)
    bee(-220, 130, 90)
    bee(-70, 60, 100)

    t.up()
    t.home()

sunshine()
t.done()
